### ISSUE TITLE
Markdown Parser

### ISSUE THREAD

**Issue by matthewtrask** [matthewtrask/elephpant-traders#14]
I brought in the League/CommonMark, but I need to write a service to actually use it.

**Comment by colinodell** [comment]
Maybe take a look at https://github.com/GrahamCampbell/Laravel-Markdown?

**Comment by matthewtrask** [comment]
I think I already have it in place, just gotta use it, and also test that it works. For some reason, I prefer to use non-laravel packages.

**Comment by matthewtrask** [comment]
closed with #35
