### ISSUE TITLE
Don't show login/register links when already logged in

### ISSUE THREAD

**Issue by railto** [matthewtrask/elephpant-traders#24]
Currently when you are logged in it still shows you the register and login links and allows you to click them to get to the forms.

At the very least these should be hidden / replaced with Profile etc.

I'll stick a PR in for this when I get time.

**Comment by matthewtrask** [comment]
Yea, this is a Laravel Auth problem I am having a hard time figuring out. Its annoyed me greatly.

**Comment by matthewtrask** [comment]
I found a way around this. Will require a lot of work, but its actually a good thing

**Comment by matthewtrask** [comment]
closed with #28
