### ISSUE TITLE
When Creating User Locally, SQL Error 1364, Field 'image' doesn't have a default value...

### ISSUE THREAD

**Issue by fskirschbaum** [matthewtrask/elephpant-traders#26]
Just saw this attempting to register an account for myself locally. 

Easy enough to fix to actually work on issue I wanted to do to contribute, but thought I'd write up an issue anyway.

```
[2017-08-29 21:57:42] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 1364 Field 'image' doesn't have a default value in /home/vagrant/elephpant-traders/vendor/laravel/framework/src/Illuminate/Database/Connection.php:449
Stack trace: ...
```

Sure enough, create syntax for that table shows `NOT NULL`.

<hashtag>AMA

**Comment by fskirschbaum** [comment]
Interesting, looks like that should be handled by 4c76d592546f7a4b9cf4a6f2e89341ae61b4cd39

**Comment by matthewtrask** [comment]
it needs to be set to null, which isn't in a migrant. One minute and Ill have it fixed :)

**Comment by matthewtrask** [comment]
fixed in 8c23fc8

**Comment by fskirschbaum** [comment]
Yeah, I fixed the locally. Wasn't sure about doing PR for it and then was
digging into posts, discovering the lack of AWS credentials.

Was going to work on a couple partials for Facebook and Twitter meta tags.

**Comment by matthewtrask** [comment]
the .env.example should have the fields for the AWS creds, which helped I hope.

**Comment by fskirschbaum** [comment]
Perfect, I'll roll back mine and delete, update and use yours. 👍

**Comment by matthewtrask** [comment]
awesome, thanks for the feedback! Lemme know if you have any other issues!
