### ISSUE TITLE
Getting a `401` when trying to post to my wishlist

### ISSUE THREAD

**Issue by tjlytle** [matthewtrask/elephpant-traders#44]
Error response is `{"error":"Unauthenticated."}` Screencast attached.

![elephpant](https://user-images.githubusercontent.com/125074/36381521-d537675c-1553-11e8-9cfe-7f91a6fae30e.gif)

**Comment by Brunty** [comment]
Beat me to it! I'm getting the same thing.

**Comment by matthewtrask** [comment]
Ah, I missed this yesterday, Ill fix it tonight sorry about that!

**Comment by matthewtrask** [comment]
May have a fix now, Ill deploy then I gotta go to work (I think)

**Comment by matthewtrask** [comment]
@tjlytle @Brunty fixed.
