### ISSUE TITLE
API returns 401 when trying to add elePHPant to wishlist

### ISSUE THREAD

**Issue by asgrim** [matthewtrask/elephpant-traders#46]
https://elephpanttrade.com/profile/elephpant/wishlist/add

*Reproduce:*

 * I check I'm definitely logged in 
 * I enter "Oracle" and desired "Five"
 * Click Submit
 * API returns a 401 (content below)
 * If I refresh the page I can see I'm now logged out

```json
{"error":"Unauthenticated."}
```

**Comment by matthewtrask** [comment]
@asgrim looks like this is similar to this: https://github.com/matthewtrask/elephpant-traders/issues/44

I pushed a fix out this morning, before work but haven't been able to check since. I will double check that it was fixed properly. :)

**Comment by asgrim** [comment]
Yes this works now, sorry for the duplicate of #44 !
