### ISSUE TITLE
Add some public stats like a counter

### ISSUE THREAD

**Issue by chrisspruck** [matthewtrask/elephpant-traders#54]
It might be interesting to keep a viewable count of "successful elephpant migrations" or other stats, maybe to do with locations (a la "7 total elephpants have migrated to Europe since 2017" or similar), depending on what data you'd want to capture. You'd want to consider what constitutes "successful" and how it's counted. One approach could be to have the receiver confirm arrival/delivery, or you could just count successful "matches", where people have agreed to a trade, so users don't have to come back to the site for further activity.

**Comment by matthewtrask** [comment]
just pushed up initial implementation
