### ISSUE TITLE
Can't remove an elephpant from a wishlist

### ISSUE THREAD

**Issue by akiojalehto** [matthewtrask/elephpant-traders#56]
Trying to remove an elephpant from a wishlist results a 401 response to the delete request. On the user perspective nothing happens when you click the _Remove_ link.

**Comment by matthewtrask** [comment]
Hey sorry, Ill look into this tonight. I think I know whats up

**Comment by matthewtrask** [comment]
@akiojalehto this is fixed now :)

**Comment by akiojalehto** [comment]
Great! Thanks Matt :)
